class WorldData {
    #components = new Map();
    #nextEntityId = 0;

    constructor(componentTypes = []) {
        for (const Component of componentTypes) {
            this.register(Component);
        }
    }

    // adds new component that entiies in this world data can be assined to
    register(Component) {
        if (this.#components.has(Component)) {
            throw new Error(`Component already registered: ${Component.name}`);
        }
        this.#components.set(Component, new Map());
    }

    // Map<entity, value> for the given Component
    #storage(Component) {
        const storage = this.#components.get(Component);
        if (!storage) {
            throw new Error(`Component not registered: ${Component.name}`);
        }
        return storage;
    }

    // gets all entity ids that have this component 
    getEntityKeys(Component) {
        return this.#storage(Component).keys();
    }

    // gets all entity value pairs with this component
    getEntityKeysAndValues(Component) {
        return this.#storage(Component).entries();
    }

    // Adds an entity to the specficed Component and the values to be assined to that component
    add(entity, Component, value) {
        this.#storage(Component).set(entity, value);
    }

    // Returns the value for an entities component. Undefined if none present
    get(entity, Component) {
        return this.#storage(Component).get(entity);
    }

    // Checks if entity has a specified component
    has(entity, Component) {
        return this.#storage(Component).has(entity);
    }

    // removes and entity from a specific component
    remove(entity, Component) {
        return this.#storage(Component).delete(entity);
    }

    // Creates the next entity always increasing. The Game is short lived enough that this should not be an issue through normal gameplay.
    // This would eventually fail and cause a crash but that would take many hours of gameplay for at most 30 minute matches.
    // If I time I would like to prevent this.
    createEntity() {
        return this.#nextEntityId++;
    }

    // Removes an entity from all associated components
    destroyEntity(entity) {
        for (const storage of this.#components.values()) {
            storage.delete(entity);
        }
    }
}


// Usage examples generated by cluade
// class Position { constructor(x, y) { this.x = x; this.y = y; } }
// class Velocity { constructor(dx, dy) { this.dx = dx; this.dy = dy; } }
// class Health   { constructor(hp) { this.hp = hp; } }

//  1. Set up world with known component types
// const world = new WorldData([Position, Velocity, Health]);

// 2. Create entities
// const player = world.createEntity();  // 0
// const enemy  = world.createEntity();  // 1

//  3. Attach components
// world.add(player, Position, new Position(0, 0));
// world.add(player, Velocity, new Velocity(1, 0));
// world.add(player, Health, new Health(100));

// world.add(enemy, Position, new Position(10, 10));
// world.add(enemy, Health, new Health(50));
// note: enemy has no Velocity — that's fine, components are optional per-entity

//  4. Query single values
// world.get(player, Health);   // Health { hp: 100 }
// world.get(enemy, Velocity);  // undefined (enemy has no Velocity)

// world.has(enemy, Velocity);  // false
// world.has(enemy, Position);  // true

//  5. Iterate a "system" — e.g. movement system only touches entities with both Position & Velocity
// for (const [entity, vel] of world.getEntityKeysAndValues(Velocity)) {
//     if (!world.has(entity, Position)) continue;
//     const pos = world.get(entity, Position);
//     pos.x += vel.dx;
//     pos.y += vel.dy;
// }

// 6. Remove a single component from an entity
// world.remove(enemy, Health); // enemy no longer has Health

// 7. Fully destroy an entity (cleans it out of every component map)
// world.destroyEntity(player);
// world.has(player, Position); // false
// world.has(player, Health);   // false


